export interface User {
 created_dt: string | Date;
 data_source_modified_dt:string | Date;
 entity_type:string;
 legal_name:string;
 dba_name?:string;
 physical_address:string;
 p_street:string;
 p_city:string;
 p_state:string;
 p_zip_code: number;
 phone:string;
 mailing_address:string;
 m_street:string;
 operating_status?:string;
 m_city:string;
 duns_number?:string;
 m_state:string;
 m_zip_code: string | number;
 usdot_number: number;
 power_units: number;
 mcs_150_form_date: number;
 drivers: number;
 mcs_150_mileage_year:string;
 id: string;
 mc_mx_ff_number?:string;
 credit_score:string;
 record_status:string;
 out_of_service_date?:string;
}
